# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: "staging"

config: {}
secrets: {}

concurrencyPolicy: Forbid
startingDeadlineSeconds: 200
successfulJobsHistoryLimit: 3

vaultK8sAuth: false

image:
  repository: eu.gcr.io/alexishr-infra/alexis-microservice
  tag: master
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 500Mi

volumes: []
volumeMounts: []

schedule: "0 * * * *"
command:
- "sh"
- "/entrypoint.sh"

spotTolerant: false
nodeSelector: false
