apiVersion: v2
description: 'Linkerd gives you observability, reliability, and security for your
  microservices — with no code change required. '
home: https://linkerd.io
icon: https://linkerd.io/images/logo-only-200h.png
keywords:
- service-mesh
maintainers:
- email: cncf-linkerd-dev@lists.cncf.io
  name: Linkerd authors
  url: https://linkerd.io/
name: linkerd-crds
sources:
- https://github.com/linkerd/linkerd2/
type: application
version: 1.4.0
