{{ if .Values.dnscrd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dnscrd.config.name }}
  namespace: {{ .Values.dnscrd.config.namespace }}
data:
  {{ range $key, $value := .Values.dnscrd.config.data }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{ end }}
{{ end }}
