{{- if .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "origin-ca-issuer.fullname" . }}-controller
  labels:
    app: {{ template "origin-ca-issuer.name" . }}
    app.kubernetes.io/name: {{ template "origin-ca-issuer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "controller"
    helm.sh/chart: {{ template "origin-ca-issuer.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "origin-ca-issuer.fullname" . }}-controller
subjects:
  - name: {{ template "origin-ca-issuer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
{{- end }}
