{{- range $cronjob := $.Values.cronjobs }}

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $cronjob.id }}"
  labels:
    chart: '{{ $cronjob.id }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app.kubernetes.io/processType: cron-job
        spec:
          restartPolicy: "Never"
          {{ if .Values.spotTolerant }}
          tolerations:
            - key: scheduling.cast.ai/spot
              operator: Exists
          {{ end }}
          {{ if .Values.nodeSelector }}
          nodeSelector:
{{ toYaml .Values.nodeSelector | indent 12 }}
          {{ end }}
          containers:
            - name: {{ $cronjob.id }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: "{{ .Values.config }}"
                - secretRef:
                    name: "{{ .Values.secrets }}"              
              env:
                - name: VAULT_ADDR
                  value : "{{ .Values.vaultArddr }}"
                # - name: VAULT_TOKEN
                #   value : "{{ .Values.vaultToken }}"
                - name: VAULT_ROLE_NAME
                  value : "{{ .Values.vaultRole }}"                    
                - name: NAMESPACE
                  value : "{{ .Values.appNamespace }}"
                - name: APP_NAME
                  value : "{{ .Values.appName }}"
                - name: COMMAND
                  value : "{{ .Values.appCommand }}"              
                - name: PROCESS_TYPE
                  value : "cron-job"
              command:
                {{- range .Values.command }}
                - {{ . }} {{- end}}
              {{ if .Values.volumeMounts }}
              volumeMounts:
{{ toYaml .Values.volumeMounts | indent 14 }}
              {{ end }}
              resources:
                limits:
                  cpu: "{{ .Values.resources.limits.cpu }}"
                  memory: "{{ .Values.resources.limits.memory }}"
                requests:
                  cpu: "{{ .Values.resources.requests.cpu }}"
                  memory: "{{ .Values.resources.requests.memory }}"
          {{- if .Values.volumes }}
          volumes:
{{ toYaml .Values.volumes | indent 10 }}
          {{- end }}


{{- end }}