{{- range $cronjob := $$cronjob.cronjobs }}

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $cronjob.id }}"
  labels:
    cronjob: '{{ $cronjob.id }}'
spec:
  schedule: "{{ $cronjob.schedule }}"
  concurrencyPolicy: {{ $cronjob.concurrencyPolicy }}
  startingDeadlineSeconds: {{ $cronjob.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ $cronjob.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app.kubernetes.io/processType: cron-job
        spec:
          restartPolicy: "Never"
          {{ if $cronjob.spotTolerant }}
          tolerations:
            - key: scheduling.cast.ai/spot
              operator: Exists
          {{ end }}
          {{ if $cronjob.nodeSelector }}
          nodeSelector:
{{ toYaml $cronjob.nodeSelector | indent 12 }}
          {{ end }}
          containers:
            - name: {{ $cronjob.id }}
              image: "{{ $cronjob.image.repository }}:{{ $cronjob.image.tag }}"
              imagePullPolicy: {{ $cronjob.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: "{{ $cronjob.config }}"
                - secretRef:
                    name: "{{ $cronjob.secrets }}"              
              env:
                - name: VAULT_ADDR
                  value : "{{ $cronjob.vaultArddr }}"
                # - name: VAULT_TOKEN
                #   value : "{{ $cronjob.vaultToken }}"
                - name: VAULT_ROLE_NAME
                  value : "{{ $cronjob.vaultRole }}"                    
                - name: NAMESPACE
                  value : "{{ $cronjob.appNamespace }}"
                - name: APP_NAME
                  value : "{{ $cronjob.appName }}"
                - name: COMMAND
                  value : "{{ $cronjob.appCommand }}"              
                - name: PROCESS_TYPE
                  value : "cron-job"
              command:
                {{- range $cronjob.command }}
                - {{ . }} {{- end}}
              {{ if $cronjob.volumeMounts }}
              volumeMounts:
{{ toYaml $cronjob.volumeMounts | indent 14 }}
              {{ end }}
              resources:
                limits:
                  cpu: "{{ $cronjob.resources.limits.cpu }}"
                  memory: "{{ $cronjob.resources.limits.memory }}"
                requests:
                  cpu: "{{ $cronjob.resources.requests.cpu }}"
                  memory: "{{ $cronjob.resources.requests.memory }}"
          {{- if $cronjob.volumes }}
          volumes:
{{ toYaml $cronjob.volumes | indent 10 }}
          {{- end }}


{{- end }}