apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-watcher
  labels:
    app: pod-watcher
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pod-watcher
  template:
    metadata:
      labels:
        app: pod-watcher
    spec:
      serviceAccountName: pod-watcher-sa
      containers:
      - name: watcher
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["cron", "-f"]
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        volumeMounts:
        - name: config
          mountPath: /etc/k8s_service_host
          subPath: k8s_service_host
      volumes:
      - name: config
        configMap:
          name: pod-watcher-config
