apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels:
    chart: '{{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.worker.replicaCount }}
  strategy:
    type: {{ .Values.worker.strategy.type }}
{{ if eq .Values.worker.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.worker.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.worker.strategy.rollingUpdate.maxSurge }}
{{ end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-selector"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-selector"
        app.kubernetes.io/processType: worker
      annotations:
        checksum/config: {{ tpl (toYaml .Values.config) . | sha256sum }}
        checksum/secrets: {{ tpl (toYaml .Values.secrets) . | sha256sum }}
    spec:
      {{ if .Values.worker.spotTolerant }}
      tolerations:
        - key: scheduling.cast.ai/spot
          operator: Exists
      {{ end }}
      {{ if .Values.worker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.worker.nodeSelector | indent 10 }}
      {{ end }}
      containers:
      - name: "{{ .Release.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          {{- range .Values.worker.command }}
          - {{ . }} {{- end}}
        {{ if .Values.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 10 }}
        {{ end }}
        ports:
        - containerPort: {{ .Values.containerPort}}
        resources:
          limits:
            cpu: "{{ .Values.worker.resources.limits.cpu }}"
            memory: "{{ .Values.worker.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.worker.resources.requests.cpu }}"
            memory: "{{ .Values.worker.resources.requests.memory }}"
        envFrom:
          {{- if and .Values.config (not (empty .Values.config)) }}
          - configMapRef:
              name: "{{ .Values.config }}"
          {{- end }}
          {{- if and .Values.secrets (not (empty .Values.secrets)) }}
          - secretRef:
              name: "{{ .Values.secrets }}"
          {{- end }}
        env:
          - name: WORKER_PORT
            value : "{{ .Values.containerPort }}"
          - name: PROCESS_TYPE
            value : "worker"
          - name: VAULT_ADDR
            value : "{{ .Values.vaultArddr }}"
          # - name: VAULT_TOKEN
          #   value : "{{ .Values.vaultToken }}"
          - name: VAULT_ROLE_NAME
            value : "{{ .Values.vaultRole }}"
          - name: K8S_AUTH
            value: "{{ .Values.vaultK8sAuth }}"
          - name: NAMESPACE
            value : "{{ .Values.appNamespace }}"
          - name: APP_NAME
            value : "{{ .Values.appName }}"
          - name: COMMAND
            value : "{{ .Values.appCommand }}"
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
      {{- if .Values.volumes }}
      volumes:
{{ toYaml .Values.volumes | indent 10 }}
      {{- end }}
