apiVersion: v1
appVersion: 0.5.1
description: A Helm chart for origin-ca-issuer
home: https://github.com/cloudflare/origin-ca-issuer
keywords:
- cert-manager
- cloudflare
- tls
name: origin-ca-issuer
sources:
- https://github.com/cloudflare/origin-ca-issuer
version: 0.5.0
