{{ if .Values.migration.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-migration"
  labels:
    chart: '{{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  schedule: "{{ .Values.migration.schedule }}"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app.kubernetes.io/processType: migration
        spec:
          restartPolicy: "Never"
          containers:
            - name: {{ .Release.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: "{{  .Release.Name }}-env-config"
                - secretRef:
                    name: "{{  .Release.Name }}-env-secrets"
              command:
              - "/bin/bash"
              - "-c"
              args:
              - "{{ .Values.migration.command }}"
              resources:
                limits:
                  cpu: "{{ .Values.migration.resources.limits.cpu }}"
                  memory: "{{ .Values.migration.resources.limits.memory }}"
                requests:
                  cpu: "{{ .Values.migration.resources.requests.cpu }}"
                  memory: "{{ .Values.migration.resources.requests.memory }}"
              {{ if .Values.volumeMounts }}
              volumeMounts:
{{ toYaml .Values.volumeMounts | indent 14 }}
              {{ end }}
          {{- if .Values.volumes }}
          volumes:
{{ toYaml .Values.volumes | indent 10 }}
          {{- end }}
{{ end}}
