{{ if .Values.worker.enabled }}
{{ if .Values.worker.pdb.enabled }}
{{ if gt (int (toString (.Values.worker.replicaCount))) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Release.Name }}-worker-deployment-pdb"
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      app: "{{  .Release.Name }}-worker-selector"
{{ end }}
{{ end }}
{{ end }}
