{{- if and .Values.secrets (not (empty .Values.secrets)) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-env-secrets"
type: Opaque
data:
{{ toYaml .Values.secrets | indent 2 }}
{{- end }}
