apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "false"
  name: "{{  .Release.Name }}-service"
  labels:
    chart: "{{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http  
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
  selector:
    app: "{{  .Release.Name }}-server-selector"
