{{ if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-server-deployment"
  labels:
    chart: '{{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.server.strategy.type }}
{{ if eq .Values.server.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.server.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.server.strategy.rollingUpdate.maxSurge }}
{{ end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-server-selector"
  template:
    metadata:
      labels:
        app: "{{  .Release.Name }}-server-selector"
        app.kubernetes.io/processType: server
      annotations:
        checksum/config: {{ tpl (toYaml .Values.config) . | sha256sum }}
        checksum/secrets: {{ tpl (toYaml .Values.secrets) . | sha256sum }}
        {{- if eq true .Values.linkerd }}
        linkerd.io/inject: enabled
        {{ end }}
    spec:
      {{ if .Values.server.spotTolerant }}
      tolerations:
        - key: scheduling.cast.ai/spot
          operator: Exists
      {{ end }}
      {{ if .Values.server.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.server.nodeSelector | indent 12 }}
      {{ end }}
{{ if .Values.server.podAntiAffinity.enabled }}
{{ if gt (int (toString (.Values.replicaCount))) 1 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - "{{ .Release.Name }}-server-selector"
                topologyKey: "kubernetes.io/hostname"
              weight: 100
{{ end }}
{{ end }}
      containers:
      - name: "{{ .Release.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          {{- range .Values.server.command }}
          - {{ . }} {{- end}}
        {{ if .Values.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 10 }}
        {{ end }}
        ports:
        - containerPort: {{ .Values.containerPort}}
        resources:
          limits:
            {{- if .Values.server.resources.limits.cpu }}
            cpu: "{{ .Values.server.resources.limits.cpu }}"
            {{ end }}
            memory: "{{ .Values.server.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.server.resources.requests.cpu }}"
            memory: "{{ .Values.server.resources.requests.memory }}"
        env:
          - name: PORT
            value : "{{ .Values.containerPort }}"
          - name: PROCESS_TYPE
            value : "server"
          - name: VAULT_ADDR
            value : "{{ .Values.vaultArddr }}"
          # - name: VAULT_TOKEN
          #   value : "{{ .Values.vaultToken }}"
          - name: VAULT_ROLE_NAME
            value : "{{ .Values.vaultRole }}"                    
          - name: NAMESPACE
            value : "{{ .Values.appNamespace }}"
          - name: APP_NAME
            value : "{{ .Values.appName }}"
          - name: COMMAND
            value : "{{ .Values.appCommand }}"  
        envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-env-config"
          - secretRef:
              name: "{{ .Release.Name }}-env-secrets"
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
      {{- if .Values.volumes }}
      volumes:
{{ toYaml .Values.volumes | indent 10 }}
      {{- end }}
{{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{  .Release.Name }}-env-config"
data:
{{ toYaml .Values.config | indent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-env-secrets"
type: Opaque
data:
{{ toYaml .Values.secrets | indent 2 }}

---
