apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "false"
  name: "{{  .Release.Name }}-service"
  labels:
    chart: "{{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .containerPort }}
{{- end }}
  selector:
    app: "{{  .Release.Name }}-server-selector"
