{{ if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-worker-deployment"
  labels:
    chart: '{{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.worker.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-worker-selector"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-worker-selector"
        app.kubernetes.io/processType: worker
      annotations:
        checksum/config: {{ tpl (toYaml .Values.config) . | sha256sum }}
        checksum/secrets: {{ tpl (toYaml .Values.secrets) . | sha256sum }}
    spec:
      nodeSelector:
        env: "{{ .Values.environment }}"
{{ if gt (int (toString (.Values.worker.replicaCount))) 1 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - "{{ .Release.Name }}-worker-selector"
                  - key: app.kubernetes.io/processType
                    operator: In
                    values:
                      - worker
              topologyKey: "kubernetes.io/hostname"
{{ end }}
      containers:
      - name: "{{ .Release.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - "/bin/bash"
          - "-c"
        args:
          - "{{ .Values.worker.command }}"
        {{ if .Values.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 10 }}
        {{ end }}
        ports:
        - containerPort: {{ .Values.containerPort}}
        resources:
          limits:
            cpu: "{{ .Values.worker.resources.limits.cpu }}"
            memory: "{{ .Values.worker.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.worker.resources.requests.cpu }}"
            memory: "{{ .Values.worker.resources.requests.memory }}"
        env:
          - name: WORKER_PORT
            value : "{{ .Values.containerPort }}"
          - name: PROCESS_TYPE
            value : "worker"
        envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-env-config"
          - secretRef:
              name: "{{ .Release.Name }}-env-secrets"
        {{- if .Values.image.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.image.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.image.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.image.readinessProbe | indent 10 }}
        {{- end }}
      {{- if .Values.volumes }}
      volumes:
{{ toYaml .Values.volumes | indent 10 }}
      {{- end }}
{{ end }}
